[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
force = true
solc_version = '0.8.12'
optimizer = true
optimizer_runs = 100000
verbosity = 3
gas_reports = ["*"]

# See more config options https://github.com/gakonst/foundry/tree/master/config